const mongoose = require('mongoose');

const lobbySchema = new mongoose.Schema({
    caffe1: {type: String, required: true},
    descriptionCaffe1: {type: String, required: true},
    imgCaffe1: {type: String, required: true},
    caffe2: {type: String, required: true},
    descriptionCaffe2: {type: String, required: true},
    imgCaffe2: {type: String, required: true},
    caffe3: {type: String, required: true},
    descriptionCaffe3: {type: String, required: true},
    imgCaffe3: {type: String, required: true},
    cocktail1: {type: String, required: true},
    descriptionCocktail1: {type: String, required: true},
    imgCocktail1: {type: String, required: true},
    cocktail2: {type: String, required: true},
    descriptionCocktail2: {type: String, required: true},
    imgCocktail2: {type: String, required: true},
    cocktail3: {type: String, required: true},
    descriptionCocktail3: {type: String, required: true},
    imgCocktail3: {type: String, required: true},
    whiskey: {type: String, required: true},
    descriptionWhiskey: {type: String, required: true},
    imgWhiskey: {type: String, required: true},
    champagne: {type: String, required: true},
    descriptionChampagne: {type: String, required: true},
    imgChampagne: {type: String, required: true},
    vodka: {type: String, required: true},
    descriptionVodka: {type: String, required: true},
    imgVodka: {type: String, required: true},
    tequila: {type: String, required: true},
    descriptionTequila: {type: String, required: true},
    imgTequila: {type: String, required: true},
    beer: {type: String, required: true},
    descriptionBeer: {type: String, required: true},
    imgBeer: {type: String, required: true},
    hookah: {type: String, required: true},
    descriptionHookah: {type: String, required: true},
    imgHookah: {type: String, required: true},
    sandwiches: {type: String, required: true},
    descriptionSandwiches: {type: String, required: true},
    imgSandwiches: {type: String, required: true},
    sweets: {type: String, required: true},
    descriptionSweets: {type: String, required: true},
    imgSweets: {type: String, required: true},
});

const Lobby = new mongoose.model('Lobby', lobbySchema);

module.exports = Lobby;